lopstore/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :games

  root 'games#index'

end

lopstore/app/models/game.rb
class Game < ActiveRecord::Base

  def poster
    "#{poster_url}"
  end
end

lopstore/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

lopstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lopstore/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :release_year, :price, :description, :poster_url)
    end
end

lopstore/app/helpers/application_helper.rb
module ApplicationHelper
end

lopstore/app/helpers/games_helper.rb
module GamesHelper
end

lopstore/app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :release_year %><br>
    <%= f.number_field :release_year %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :poster_url %><br>
    <%= f.text_field :poster_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lopstore/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

lopstore/app/views/games/index.html.erb
<h4 class="column">Featured Games</h4>
<div class="column">
  <ul class="games-grid no-bullet row">
    <% @games.each do |game| %>
      <li class="large-3 medium-4 small-12 column">
        <div class="game-card padly">
          <%= link_to game, class: "poster" do %>
            <%= image_tag game.poster %>
          <% end %>
          <div class="game-info ell glassy-bg padmy padlx">
            <div class="title">
              <h6><%= game.title %> <span>(<%= game.release_year %>)</span></h6>
            </div>
            <p class="left price label game-label radius">$ <%= game.price %></p>
            <% end %>
          </div>
        </div>
      </li>

  </ul>
</div>

lopstore/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

lopstore/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<div class="large-3 small-12 column">
  <%=image_tag @game.poster%>
</div>

<div class="large-9 small-12 column">
  <h3>
    <%= @game.title %>
    (<%= @game.release_year %>)
    <%end%>
  </h3>
  <p class="label game-label radius mb1">$ <%= @game.price %></p>
 <%end%>
  <%end%>
  <p><%= @game.description %></p>
</div>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

lopstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application.scss" %>
    <%= javascript_include_tag "application.scss", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render "layouts/header" %>

  <%= render "layouts/alerts" %>

  <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>

  <footer class="row">
    <div class="large-12 columns">
      <hr> <p>© LOP 2016</p>
    </div>
  </footer>

  <%= javascript_include_tag "application.scss" %>

</body>
</html>